### ISSUE TITLE
[bug]body._method.toUpperCase is not a function

### ISSUE THREAD

**Issue by logzh** [node-modules/koa-override#5]
![image](https://user-images.githubusercontent.com/9158889/103472300-01440e00-4dc7-11eb-8fec-ea61acf29ef2.png)

![image](https://user-images.githubusercontent.com/9158889/103472307-102ac080-4dc7-11eb-8149-1356ea455f8a.png)

```
nodejs.TypeError: body._method.toUpperCase is not a function
    at overrideMethod (/data/xx/node_modules/koa-override/index.js:19:29)
    at dispatch (/data/xx/node_modules/koa-compose/index.js:42:32)
    at bodyParser (/data/xx/node_modules/koa-bodyparser/index.js:86:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /data/xx/node_modules/koa-static-cache/index.js:51:63
    at async notfound (/data/xx/node_modules/@xxx/xxx/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/data/xx/node_modules/@xxx/xxx/node_modules/egg/app/middleware/meta.js:12:5)
    at async healthy (/data/xx/node_modules/egg-healthy/app/middleware/egg_healthy.js:21:5)
```

https://github.com/node-modules/koa-override/blob/master/index.js#L19

**Comment by fengmk2** [comment]
https://github.com/eggjs/koa-override/pull/7
